### ISSUE TITLE
Add support for focused/unfcused window opacity

### ISSUE THREAD

**Issue by rfgamaral** [lucleray/hyper-opacity#2]
Instead of having a single opacity configuration, add an option to set a different opacity when the window is not focused (or the other way around, depends on how you want to name the configuration options).

For instance, keep the current `opacity` option (for compatibility reasons) and add a new one, `inactiveOpacity` for when the Hyper window is not focused.

**Comment by lucleray** [comment]
It's already released !

I guess you can uninstall/install to get it :
```
hyper u hyper-opacity
hyper i hyper-opacity
```

**Comment by rfgamaral** [comment]
I though you're going to change the plugin version and since I kept seeing `0.0.6` I thought it wasn't updated. Sorry for the confusion.

**Comment by lucleray** [comment]
No problem 🙂

 I changed it, it's 1.0.0 now 🍾
