### ISSUE TITLE
Support for Linux

### ISSUE THREAD

**Issue by plibither8** [lucleray/hyper-opacity#3]
I run Ubuntu 16.04 and I'd really want this plugin to work on Linux. Is there a plan to bring in support for Linux too?

Thanks

**Comment by lucleray** [comment]
Hi,

I'm looking for a solution to bring it to Linux, but at the moment I haven't found any.

If you have any idea, your help is welcome 🙂

(I'm using this API of electron : https://electronjs.org/docs/api/browser-window#winsetopacityopacity-windows-macos)

**Comment by plibither8** [comment]
Ahh it’s quite a deep rooted problem if the electron API itself doesn’t support it. Thanks though! :)

**Comment by emmanuelnk** [comment]
Here's a workaround till this is implemented in Linux.

On Ubuntu you can use devilspie to add opacity to any window. I did this with vscode and it works really well. The window name for hyperjs in linux (tested ubuntu 18.04) is `Hyper`

First, install devilspie
`sudo apt-get install devilspie`
then
`cd ~/.devilspie/` (or `mkdir ~/.devilspie/ && cd ~/.devilspie/` if it doens't exist yet.)

then
`touch hyper_opacity.ds` (I usually make a seperate `.ds` file for each specific devispie task) 
`nano hyper_opacity.ds` (or your favorite text editor)
copy into the file this script:
```
( if
( contains ( window_class ) "Hyper" )
( begin
( spawn_async (str "xprop -id " (window_xid) " -f _NET_WM_WINDOW_OPACITY 32c -set _NET_WM_WINDOW_OPACITY 0xedffffff") )
)
)

```
Take note of `_NET_WM_WINDOW_OPACITY 0xedffffff`. The first two digits in that HEX number (`ed`) will determine the opacity. Minimum is 1 and max is 255, but in HEX. So if you want 0.9 opacity, then you do `0.9 * 255` and then convert the result to hex. You can use this [tool ](https://www.binaryhexconverter.com/decimal-to-hex-converter).

save the file and then from the console, run: `devilspie` 

This will run all `.ds` files you have in the folder `~/.devilspie`. You could also have separate `.ds` for `vscode` and `sublime` using the window names `Code` and `Subl`, you get the gist of it. the cmd `devispie` will load all of them. 

All your windows should become transparent. You can then configure the command `devilspie` to always run in the background. I'll leave that up to you reader.

**Comment by lucleray** [comment]
That's interesting @emmanuelnk. Have you tried `transset` ? 

It works like this : `transset -a 0.85` ([see the docs here](https://www.systutorials.com/docs/linux/man/1-transset/)).

**Comment by emmanuelnk** [comment]
@lucleray I actually tried transset when I was using KDE a while back but I think it was broken (windows would hang after some minutes) so I never got round to using it again. I'll try it again though.
