### ISSUE TITLE
Error in Hyper 3

### ISSUE THREAD

**Issue by sandhilt** [lucleray/hyper-opacity#7]
This is message error when I try open:
![image](https://user-images.githubusercontent.com/6170125/57343990-de59e600-711b-11e9-9886-c249277e57b2.png)

Specs
![image](https://user-images.githubusercontent.com/6170125/57344053-2b3dbc80-711c-11e9-8c55-5774234a6f22.png)

**Comment by sandhilt** [comment]
In ``.hyper``, ``plugins`` field is ``hyper-opacity`` and not `` opacity ``.

**Comment by devandanger** [comment]
I saw the same error but it was because I didn't set the plugins correctly.

plugins: ["hyperpower, hyper-opacity"], // set it up as a string comma-limited oppose to typical string array.
